### ISSUE TITLE
It's not clear from README how to specify multiple dependencies in short form

### ISSUE THREAD

**Issue by vi** [DanielKeep/cargo-script#15]
In README there is example:

    // cargo-deps: time="0.1.25"

But what if there are two dependencies? How to specify them then?

```
// cargo-deps: time="0.1.25" env-logger="*"
```

```
// cargo-deps: time="0.1.25", env-logger="*"
```

```
// cargo-deps: time="0.1.25" 
// cargo-deps: env-logger="*"
```

I'd prefer all three to work.

**Comment by DanielKeep** [comment]
It's comma-separated.  I'm not inclined to support no commas, since the syntax is really just inline TOML.  I'm *disinclined* to support the second, because if you have enough dependencies to justify multiple lines, I'd rather people use an embedded manifest.
