### ISSUE TITLE
Code block manifest uses first doc comment *anywhere* in script

### ISSUE THREAD

**Issue by DanielKeep** [DanielKeep/cargo-script#4]
The comment extraction is supposed to only allow a crate doc comment that is the first thing in the file after the hashbang.  Currently, it doesn't enforce this.  It should.

Fix would be to modify the search to abort if it finds anything that isn't whitespace.

**Comment by durka** [comment]
As a corollary to this, it fails with an internal error if there is no doc comment at all (but an empty `//!` satisfies it).

**Comment by DanielKeep** [comment]
Urgh.  What *asshole* wrote this garbage?
