### ISSUE TITLE
Can't pass args starting with dash

### ISSUE THREAD

**Issue by Boscop** [DanielKeep/cargo-script#40]
```
cargo script -- foo "-N2NH6"
error: Found argument '-N' which wasn't expected, or isn't valid in this context
```
Same error without the quotes.
The dash is part of the arg value.
How to escape the dash?

**Comment by DanielKeep** [comment]
This should be fixed with the update to clap.

Also, I don't know why Github bothers to parse commit messages if it won't actually close the damn issue.  \**sigh*\*
