### ISSUE TITLE
full toml header

### ISSUE THREAD

**Issue by vitiral** [DanielKeep/cargo-script#44]
I love the idea of this!

One thing that I think would be very useful is a full toml header. I propose the following syntax -- which must be followed EXACTLY:
```
# CARGO SCRIPT
`` `
[dependencies]
toml = "4.2.3"
# ... etc
`` `
*/
```

Basically we will just do a regex for 
```
# CARGO SCRIPT\n\`\`\`(.*)\`\`\`
```
(also enable multi-line mode) and we will allow the user to specify the full Cargo.toml!

This will automatically fill in required non-dependency details (package.name and package.version), unless they are specified in which case it won't touch them.

**Comment by vitiral** [comment]
I can work on this if you agree. Would like to know your thoughts on the format too.

**Comment by DanielKeep** [comment]
I'm confused; how is this functionally different to the existing support for manifests?

**Comment by vitiral** [comment]
sorry, I just didn't see it in the docs. Thanks!
