### ISSUE TITLE
cargo-script interface via "cargo script" is incorrect with nightly-2018-03-20

### ISSUE THREAD

**Issue by tcr** [DanielKeep/cargo-script#54]
I just switched to this nightly, and cargo script suddenly fails to work. Note the help menu:

```
$ cargo script
cargo 0.2.8
Compiles and runs "Cargoified Rust scripts".

USAGE:
    cargo <SUBCOMMAND>

FLAGS:
    ...
```

`cargo-script` seems to think it's a binary named `cargo`, not `cargo-script` as intended.

The `run-cargo-script` binary is also affected.

**Workaround:** Adding script as the third argument, as in `cargo script script filename.rs` seems to work.

**Comment by ryansname** [comment]
@tcr I think thats related to this: https://github.com/rust-lang/cargo/issues/5212.

It worked for me after upgrading from nightly 2018-03-19 to 2018-03-28.

**Comment by tcr** [comment]
@ryansname is correct, this looks resolved and was fixed for me in 2018-03-30. :)
