### ISSUE TITLE
src/platform: no method named: '.as_raw'

### ISSUE THREAD

**Issue by nathanross** [DanielKeep/cargo-script#6]
To get cargo-script to compile with nightly, I just changed platform.rs:47 from ```md.as_raw.mtime()``` to ```md.mtime()```.

But I don't know enough about those modules' previous syntax or this project to say if that'll bork expected behavior, so just submitting this as an issue.

**Comment by DanielKeep** [comment]
This ended up in your PR, so I just merged it.  Seems fine.
