### ISSUE TITLE
Support for Rust 2018 edition

### ISSUE THREAD

**Issue by ErichDonGubler** [DanielKeep/cargo-script#66]
It'd be nice if we could just add this to the embedded manifest and just be good to go, like with normal `cargo` manifests, once the new edition is out:

```
//! ```cargo
//! edition = "2018"
//! ...
//! ```
```

**Comment by theduke** [comment]
This works for me with: 

```
//! ```cargo
//! [package]
//! edition = "2018"
//!
//! [dependencies]
//! ```
```

(Apart from the probably unrelated hanging issue #67 )

**Comment by ErichDonGubler** [comment]
Ahhh...my mistake was not using the `[package]` key header. It works for me! Thank you! :)

**Comment by Avi-D-coder** [comment]
The default should be `edition = "2018"`

**Comment by theduke** [comment]
Yeah it should, but considering that the last commit was on Oct 29, 2017, it is fair to say that this crate is unmaintained.

You can check out https://github.com/fanzeyi/cargo-play as an alternative.
